# Generated by Django 3.2.8 on 2021-10-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone1', models.CharField(max_length=30, verbose_name='Телефон-1')),
                ('phone2', models.CharField(max_length=30, verbose_name='Телефон-2')),
                ('mail', models.EmailField(max_length=254, verbose_name='Почта')),
                ('fb', models.URLField(verbose_name='Ссылка на facebook')),
                ('inst', models.URLField(verbose_name='Ссылка на instagram')),
                ('google', models.URLField(verbose_name='Ссылка на google')),
                ('address_office', models.CharField(max_length=500, verbose_name='Адрес офиса')),
                ('address_legal', models.TextField(max_length=500, verbose_name='Юридический адрес')),
                ('fax', models.CharField(max_length=30, verbose_name='Факс')),
            ],
            options={
                'verbose_name': 'Контактные данные',
                'verbose_name_plural': 'Контактные данные',
            },
        ),
    ]
