# Generated by Django 3.2.8 on 2021-10-22 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.TextField(max_length=3000, verbose_name='Описание миссии')),
            ],
            options={
                'verbose_name': 'Страница - Главная',
                'verbose_name_plural': 'Страница - Главная',
            },
        ),
        migrations.CreateModel(
            name='PageHomeAccordion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('description', models.TextField(max_length=3000, verbose_name='Описание')),
                ('pageHome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeAccordion', to='main.pagehome')),
            ],
            options={
                'verbose_name': 'Аккордеон',
                'verbose_name_plural': 'Аккордеон',
            },
        ),
    ]
