# Generated by Django 3.2.8 on 2021-10-22 14:49

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pagehome_pagehomeaccordion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagehome',
            name='mission',
            field=tinymce.models.HTMLField(),
        ),
    ]
