# Generated by Django 3.2.8 on 2021-10-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_pagehome_mission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagehome',
            name='mission',
            field=models.TextField(max_length=3000, verbose_name='Описание миссии'),
        ),
    ]
