# Generated by Django 3.2.8 on 2021-10-23 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_pagehome_mission'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_office', models.CharField(max_length=500, verbose_name='Адрес офиса')),
                ('address_legal', models.TextField(max_length=500, verbose_name='Юридический адрес')),
                ('fax', models.CharField(max_length=30, verbose_name='Факс')),
            ],
            options={
                'verbose_name': 'Страница - Контакты',
                'verbose_name_plural': 'Страница - Контакты',
            },
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='address_legal',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='address_office',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='fax',
        ),
        migrations.CreateModel(
            name='PageContactsPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=300, verbose_name='Должность')),
                ('photo', models.ImageField(upload_to='contactsPeoplePhoto/', verbose_name='Фотография')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('mail1', models.EmailField(max_length=254, verbose_name='Почта-1')),
                ('mail2', models.EmailField(max_length=254, verbose_name='Почта-2')),
                ('pageContacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactsPeople', to='main.pagecontacts')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
