# Generated by Django 3.2.8 on 2021-10-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211023_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontactspeople',
            name='photo',
            field=models.ImageField(blank=True, upload_to='contactsPeoplePhoto/', verbose_name='Фотография'),
        ),
    ]
