# Generated by Django 3.2.8 on 2021-10-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_pagecontactspeople_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontactspeople',
            name='mail1',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Почта-1'),
        ),
        migrations.AlterField(
            model_name='pagecontactspeople',
            name='mail2',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Почта-2'),
        ),
        migrations.AlterField(
            model_name='pagecontactspeople',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Телефон'),
        ),
    ]
