# Generated by Django 3.2.8 on 2021-10-25 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20211023_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageAboutСompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=5000, verbose_name='Текст о компании')),
            ],
            options={
                'verbose_name': 'Страница - О компании',
                'verbose_name_plural': 'Страница - О компании',
            },
        ),
        migrations.CreateModel(
            name='PageAboutСompanyOther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=5000, verbose_name='Название')),
                ('pageAboutСompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aboutСompany', to='main.pageaboutсompany')),
            ],
            options={
                'verbose_name': 'Другая компания',
                'verbose_name_plural': 'Другие компании',
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
