# Generated by Django 3.2.8 on 2021-10-29 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20211025_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagePhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Страница - Фотогалерея',
                'verbose_name_plural': 'Страница - Фотогалерея',
            },
        ),
        migrations.CreateModel(
            name='PagePhotoGalleryProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='gallery-project/', verbose_name='Изображене проекта 1')),
                ('img2', models.ImageField(upload_to='gallery-project/', verbose_name='Изображене проекта 2')),
                ('pagePhotoGalleryProject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleryProject', to='main.pagephotogallery')),
            ],
            options={
                'verbose_name': 'Изображение проекта',
                'verbose_name_plural': 'Изображения проектов',
            },
        ),
        migrations.CreateModel(
            name='PagePhotoGalleryAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='gallery-auto/', verbose_name='Изображене автогаллереи 1')),
                ('img2', models.ImageField(upload_to='gallery-auto/', verbose_name='Изображене автогаллереи 2')),
                ('pagePhotoGalleryAuto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleryAuto', to='main.pagephotogallery')),
            ],
            options={
                'verbose_name': 'Изображение автотранспорта',
                'verbose_name_plural': 'Изображения автотранспорта',
            },
        ),
    ]
