# Generated by Django 3.2.8 on 2021-10-31 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_pagephotogallery_pagephotogalleryauto_pagephotogalleryproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageHomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='slider/', verbose_name='Изображение слайдера')),
                ('pageHome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeSlider', to='main.pagehome')),
            ],
            options={
                'verbose_name': 'Изображение слайдера',
                'verbose_name_plural': 'Изображения слайдера',
            },
        ),
    ]
