# Generated by Django 3.2.8 on 2021-10-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20211031_1903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagephotogalleryproject',
            options={'verbose_name': 'Изображение проекта', 'verbose_name_plural': 'Изображения проектов'},
        ),
        migrations.AddField(
            model_name='pagephotogalleryproject',
            name='img1',
            field=models.ImageField(default='default.jpg', upload_to='gallery-project/', verbose_name='Изображене проекта 1'),
        ),
        migrations.AddField(
            model_name='pagephotogalleryproject',
            name='img2',
            field=models.ImageField(default='default.jpg', upload_to='gallery-project/', verbose_name='Изображене проекта 2'),
        ),
    ]
