# Generated by Django 3.2.8 on 2021-10-31 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20211031_1911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagedocument',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
    ]
